### ISSUE TITLE
Install error on MAC M1

### ISSUE THREAD

**Issue by hungphamlk** [mgtcommerce/mgt-dev#10]
Hello
I installed vai this comment
"docker run -d --net=bridge -v /var/lib/mysql -v /home/cloudpanel --restart=always --privileged -h mgt-dev --name mgt-dev -it -p 80:80 -p 443:443 -p 8443:8443 -p 22:22 -p 3306:3306 -p 9200:9200 -p 15672:15672 mgtcommerce/mgt-dev:v2"

After that I am getting this error. I can not access Elasticsearch. I am using docker v4.5.0 (74594)
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
e33c70bb3986a108790e8568f4571baee2078633446705695b8ecb85e9bf48e8

**Comment by swieczorek** [comment]
Version 3 supports ARM64 and can be used on Mac M1/M2:

https://www.mgt-commerce.com/docs/mgt-development-environment/installation
