### ISSUE TITLE
403 forbidden nginx from https://magento2.mgt

### ISSUE THREAD

**Issue by Quest45** [mgtcommerce/mgt-dev#6]
I followed the installation process on your page https://www.mgt-commerce.com/docs/mgt-development-environment/installation and everything went well (I did not encounter any problems). But when I try to access the magento home page https://magento2.mgt I get this error: 403 Forbidden and when I do https://magento2.mgt/admin I get this time: 404 not found...
access.log:
  | 2021-08-20 12:04:35 | 172.17.0.1 - - [20/Aug/2021:10:04:35 +0000] "GET / 2.0" 403 130 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
-- | -- | --
  | 2021-08-20 12:04:39 | 172.17.0.1 - - [20/Aug/2021:10:04:39 +0000] "GET / 2.0" 403 130 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"
  | 2021-08-20 12:06:03 | 172.17.0.1 - - [20/Aug/2021:10:06:03 +0000] "GET / 2.0" 403 130 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36"

**Comment by WillPhoenixLiu** [comment]
I faced the same issue. Finally, it turns out I set the wrong Document Root which should be 'magento2.mgt/pub'.
